#---- Replicaset Manefests File -------

apiVersion: apps/v1 
kind: ReplicaSet
metadata:
  name: javars
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javars
    matchExpressions: # Set Based
    - key: app
      operators: not in 
      values: 
      - pythonapp
      - python
  template: #Pod Template
    metadata:
      name: javapod
      labels:
        app: javaapp
    spec:
      containers:
      - name: javaapp
        image: account1996/dockerwebapp:1
        ports:
        - containerPort: 4000

#------ With Service ( Node Port)-----------

apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
  - port: 80
    targetPort: 6000
    nodeport: 31666
